name: Build main

on:
  push:
    branches:
      - main

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build:x64
      - run: npm run build:arm64
      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          if-no-files-found: error
          path: dist/*.AppImage
          retention-days: 1

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - name: "Update experimental tag"
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "experimental"
          force_push_tag: true
          message: "Development release"
      - name: Publish release
        uses: "softprops/action-gh-release@v2"
        with:
          tag_name: "experimental"
          name: "Development release"
          body: "Latest successful build of the main branch, use at your own risks"
          prerelease: true
          draft: false
          fail_on_unmatched_files: true
          files: |
            dist/**/*.AppImage
